/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Username = IDL.Text;

export const idlService = IDL.Service({
  'login' : IDL.Func([Username, IDL.Text], [IDL.Bool], []),
  'register' : IDL.Func([Username, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Username = IDL.Text;
  
  return IDL.Service({
    'login' : IDL.Func([Username, IDL.Text], [IDL.Bool], []),
    'register' : IDL.Func([Username, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };